import type { Resume } from "@/lib/resume/schema";
import { adapt as a_vantage } from "./vantage/adapter";
import { adapt as a_swe } from "./swe/adapter";
import { adapt as a_basic_resume } from "./basic-resume/adapter";
import { adapt as a_academicv } from "./academicv/adapter";
import { adapt as a_acadennial_cv } from "./acadennial-cv/adapter";
import { adapt as a_acorn_resume } from "./acorn-resume/adapter";
import { adapt as a_ats_friendly_resume } from "./ats-friendly-resume/adapter";
import { adapt as a_bone_resume } from "./bone-resume/adapter";
import { adapt as a_brilliant_cv } from "./brilliant-cv/adapter";
import { adapt as a_butterick_resume } from "./butterick-resume/adapter";
import { adapt as a_calligraphics } from "./calligraphics/adapter";
import { adapt as a_chicv } from "./chicv/adapter";
import { adapt as a_chuli_cv } from "./chuli-cv/adapter";
import { adapt as a_clean_ats_cv } from "./clean-ats-cv/adapter";
import { adapt as a_clean_print_cv } from "./clean-print-cv/adapter";
import { adapt as a_clickworthy_resume } from "./clickworthy-resume/adapter";
import { adapt as a_cobalt_cv } from "./cobalt-cv/adapter";
import { adapt as a_curriculo_acad } from "./curriculo-acad/adapter";
import { adapt as a_fantastic_cv } from "./fantastic-cv/adapter";
import { adapt as a_finely_crafted_cv } from "./finely-crafted-cv/adapter";
import { adapt as a_free_cv } from "./free-cv/adapter";
import { adapt as a_gloat } from "./gloat/adapter";
import { adapt as a_golixp_resume_zh_cn } from "./golixp-resume-zh-cn/adapter";
import { adapt as a_grotesk_cv } from "./grotesk-cv/adapter";
import { adapt as a_guided_resume_starter_cgc } from "./guided-resume-starter-cgc/adapter";
import { adapt as a_habaneraa_one_page_resume_zh } from "./habaneraa-one-page-resume-zh/adapter";
import { adapt as a_humanistically } from "./humanistically/adapter";
import { adapt as a_imprecv } from "./imprecv/adapter";
import { adapt as a_impressive_impression } from "./impressive-impression/adapter";
import { adapt as a_jsume } from "./jsume/adapter";
import { adapt as a_kiresume } from "./kiresume/adapter";
import { adapt as a_lavandula } from "./lavandula/adapter";
import { adapt as a_light_cv } from "./light-cv/adapter";
import { adapt as a_linked_cv } from "./linked-cv/adapter";
import { adapt as a_mahou_cv } from "./mahou-cv/adapter";
import { adapt as a_metronic } from "./metronic/adapter";
import { adapt as a_minimal_cv } from "./minimal-cv/adapter";
import { adapt as a_min_resume } from "./min-resume/adapter";
import { adapt as a_minimalistic_latex_cv } from "./minimalistic-latex-cv/adapter";
import { adapt as a_modern_acad_cv } from "./modern-acad-cv/adapter";
import { adapt as a_modern_cv } from "./modern-cv/adapter";
import { adapt as a_modern_resume } from "./modern-resume/adapter";
import { adapt as a_moderner_cv } from "./moderner-cv/adapter";
import { adapt as a_modernpro_cv } from "./modernpro-cv/adapter";
import { adapt as a_mrbogo_cv } from "./mrbogo-cv/adapter";
import { adapt as a_neat_cv } from "./neat-cv/adapter";
import { adapt as a_nabcv } from "./nabcv/adapter";
import { adapt as a_nutshell } from "./nutshell/adapter";
import { adapt as a_pesha } from "./pesha/adapter";
import { adapt as a_porygon } from "./porygon/adapter";
import { adapt as a_pro_academic_cv } from "./pro-academic-cv/adapter";
import { adapt as a_rendercv } from "./rendercv/adapter";
import { adapt as a_resumania } from "./resumania/adapter";
import { adapt as a_resume_ng } from "./resume-ng/adapter";
import { adapt as a_silver_dev_cv } from "./silver-dev-cv/adapter";
import { adapt as a_simple_technical_resume } from "./simple-technical-resume/adapter";
import { adapt as a_simple_xd_resume } from "./simple-xd-resume/adapter";
import { adapt as a_cv_soft_and_hard } from "./cv-soft-and-hard/adapter";
import { adapt as a_sweet_graduate_resume } from "./sweet-graduate-resume/adapter";
import { adapt as a_toy_cv } from "./toy-cv/adapter";
import { adapt as a_ttq_classic_resume } from "./ttq-classic-resume/adapter";
import { adapt as a_typographic_resume } from "./typographic-resume/adapter";
import { adapt as a_vercanard } from "./vercanard/adapter";
import { adapt as a_vivid_cv } from "./vivid-cv/adapter";
import { adapt as a_yuan_resume } from "./yuan-resume/adapter";

/**
 * Single source of truth for resume templates. GENERATED by
 * scripts/build-registry.mjs from each src/templates/<id>/meta.json — do not
 * edit by hand; add a template dir (adapter.ts + resume.typ + meta.json) and
 * rerun the script. Each entry pairs UI metadata with the pure adapter that
 * maps a Resume into the JSON its resume.typ consumes. Most templates wrap a
 * Typst Universe package (`pkg`), auto-downloaded into the Typst cache.
 */
export interface TemplateDef {
  id: string;
  name: string;
  description: string;
  /** Swatch/accent color for the picker. */
  accent: string;
  /** Provenance: the @preview package this template renders with, if any. */
  pkg?: string;
  adapt: (r: Resume) => unknown;
}

export const TEMPLATE_DEFS: TemplateDef[] = [
  {
    id: "vantage",
    name: "Vantage",
    description: "Two-column ATS-friendly layout with an indigo accent.",
    accent: "#3730a3",
    adapt: a_vantage,
  },
  {
    id: "swe",
    name: "SWE",
    description: "Single-column engineering CV with a centered header.",
    accent: "#24449e",
    adapt: a_swe,
  },
  {
    id: "basic-resume",
    name: "Basic Resume",
    description: "Simple, standard, ATS-friendly single-column resume.",
    accent: "#26428b",
    pkg: "@preview/basic-resume",
    adapt: a_basic_resume,
  },
  {
    id: "academicv",
    name: "AcademiCV",
    description: "Clean serif academic CV with a timeline layout and blue links.",
    accent: "#3278b4",
    pkg: "@preview/academicv",
    adapt: a_academicv,
  },
  {
    id: "acadennial-cv",
    name: "Acadennial CV",
    description: "Elegant academic CV with a three-column grid and serif typography",
    accent: "#333333",
    pkg: "@preview/acadennial-cv",
    adapt: a_acadennial_cv,
  },
  {
    id: "acorn-resume",
    name: "Acorn Resume",
    description: "Clean minimal single-column resume with underlined rule headings",
    accent: "#000000",
    pkg: "@preview/acorn-resume",
    adapt: a_acorn_resume,
  },
  {
    id: "ats-friendly-resume",
    name: "ATS-Friendly Resume",
    description: "Clean single-column developer resume tuned for ATS parsing.",
    accent: "#26428b",
    pkg: "@preview/ats-friendly-resume",
    adapt: a_ats_friendly_resume,
  },
  {
    id: "bone-resume",
    name: "Bone Resume",
    description: "Colorful single-column resume with bordered section boxes and indigo headings.",
    accent: "#444488",
    pkg: "@preview/bone-resume",
    adapt: a_bone_resume,
  },
  {
    id: "brilliant-cv",
    name: "Brilliant CV",
    description: "Modular sky-blue CV with icon contact line and accent section titles.",
    accent: "#0395DE",
    pkg: "@preview/brilliant-cv",
    adapt: a_brilliant_cv,
  },
  {
    id: "butterick-resume",
    name: "Butterick Résumé",
    description: "Classic monochrome serif resume from Butterick's Practical Typography.",
    accent: "#1a1a1a",
    pkg: "@preview/butterick-resume",
    adapt: a_butterick_resume,
  },
  {
    id: "calligraphics",
    name: "Calligraphics",
    description: "Two-column resume with a generative colorful triangle accent panel.",
    accent: "#a658b8",
    pkg: "@preview/calligraphics",
    adapt: a_calligraphics,
  },
  {
    id: "chicv",
    name: "Chicv",
    description: "Minimal monochrome single-column CV with ruled section headers",
    accent: "#000000",
    pkg: "@preview/chicv",
    adapt: a_chicv,
  },
  {
    id: "chuli-cv",
    name: "Chuli CV",
    description: "Minimalist modern CV with accent headings, rule dividers, and skill/language tags",
    accent: "#007fad",
    pkg: "@preview/chuli-cv",
    adapt: a_chuli_cv,
  },
  {
    id: "clean-ats-cv",
    name: "Clean ATS CV",
    description: "Clean ATS-friendly layout with navy headings and social icons.",
    accent: "#022359",
    pkg: "@preview/clean-ats-cv",
    adapt: a_clean_ats_cv,
  },
  {
    id: "clean-print-cv",
    name: "Clean Print CV",
    description: "Print-friendly single-column CV with deep-blue accent bars, B&W-safe.",
    accent: "#2b4c7e",
    pkg: "@preview/clean-print-cv",
    adapt: a_clean_print_cv,
  },
  {
    id: "clickworthy-resume",
    name: "Clickworthy Resume",
    description: "Clean, ATS-friendly resume with smallcaps headings and linked contacts",
    accent: "#26428b",
    pkg: "@preview/clickworthy-resume",
    adapt: a_clickworthy_resume,
  },
  {
    id: "cobalt-cv",
    name: "Cobalt CV",
    description: "Two-column resume with shaded sidebar, icon contacts, cobalt accent",
    accent: "#002366",
    pkg: "@preview/cobalt-cv",
    adapt: a_cobalt_cv,
  },
  {
    id: "curriculo-acad",
    name: "Curriculo Acad",
    description: "Academic LATTES-style CV with sectioned headings and gray accents",
    accent: "#b2b2b2",
    pkg: "@preview/curriculo-acad",
    adapt: a_curriculo_acad,
  },
  {
    id: "fantastic-cv",
    name: "Fantastic CV",
    description: "Comprehensive single-column CV with smallcaps ruled sections, navy accent",
    accent: "#26428b",
    pkg: "@preview/fantastic-cv",
    adapt: a_fantastic_cv,
  },
  {
    id: "finely-crafted-cv",
    name: "Finely Crafted CV",
    description: "Elegant monochrome serif CV with dotted-leader company headings.",
    accent: "#1a1a1a",
    pkg: "@preview/finely-crafted-cv",
    adapt: a_finely_crafted_cv,
  },
  {
    id: "free-cv",
    name: "Free CV",
    description: "Spacious, colorful CV with boxed entries and FontAwesome contact icons.",
    accent: "#807eff",
    pkg: "@preview/free-cv",
    adapt: a_free_cv,
  },
  {
    id: "gloat",
    name: "Gloat",
    description: "Centered academic CV with smallcaps headings, clean and ATS-friendly.",
    accent: "#333333",
    pkg: "@preview/gloat",
    adapt: a_gloat,
  },
  {
    id: "golixp-resume-zh-cn",
    name: "Golixp Modular Resume",
    description: "Modular sidebar resume with icon section headers and tech tags",
    accent: "#26267d",
    pkg: "@preview/golixp-resume-zh-cn",
    adapt: a_golixp_resume_zh_cn,
  },
  {
    id: "grotesk-cv",
    name: "Grotesk CV",
    description: "Clean two-column CV on a warm paper background with skill tags",
    accent: "#3c3c42",
    pkg: "@preview/grotesk-cv",
    adapt: a_grotesk_cv,
  },
  {
    id: "guided-resume-starter-cgc",
    name: "Guided Resume Starter",
    description: "Clean single-column resume with smallcaps headers and ruled section lines.",
    accent: "#0645AD",
    pkg: "@preview/guided-resume-starter-cgc",
    adapt: a_guided_resume_starter_cgc,
  },
  {
    id: "habaneraa-one-page-resume-zh",
    name: "Habaneraa One-Page Resume",
    description: "Minimalist one-page resume with teal accents and a single spacing knob.",
    accent: "#179299",
    pkg: "@preview/habaneraa-one-page-resume-zh",
    adapt: a_habaneraa_one_page_resume_zh,
  },
  {
    id: "humanistically",
    name: "Humanistically",
    description: "Clean, minimal academic-style CV with right-aligned section rules",
    accent: "#222222",
    pkg: "@preview/humanistically",
    adapt: a_humanistically,
  },
  {
    id: "imprecv",
    name: "Imprecv",
    description: "No-frills single-column CV with underlined section headings.",
    accent: "#000000",
    pkg: "@preview/imprecv",
    adapt: a_imprecv,
  },
  {
    id: "impressive-impression",
    name: "Impressive Impression",
    description: "Two-column CV with a tinted sidebar and timeline-style main entries.",
    accent: "#266590",
    pkg: "@preview/impressive-impression",
    adapt: a_impressive_impression,
  },
  {
    id: "jsume",
    name: "JSume",
    description: "Clean serif single-column JSON Resume template with smallcaps section rules",
    accent: "#1a1a1a",
    pkg: "@preview/jsume",
    adapt: a_jsume,
  },
  {
    id: "kiresume",
    name: "Kiresume",
    description: "Clean single-column resume with navy headers and section dividers",
    accent: "#1a3c6e",
    pkg: "@preview/kiresume",
    adapt: a_kiresume,
  },
  {
    id: "lavandula",
    name: "Lavandula",
    description: "Modern two-column resume with a tinted sidebar and accent headings.",
    accent: "#414cc8",
    pkg: "@preview/lavandula",
    adapt: a_lavandula,
  },
  {
    id: "light-cv",
    name: "Light CV",
    description: "Minimalist CV with a bold header, ruled sections and cyan accents.",
    accent: "#007fad",
    pkg: "@preview/light-cv",
    adapt: a_light_cv,
  },
  {
    id: "linked-cv",
    name: "Linked CV",
    description: "LinkedIn-styled timeline CV with company blocks and accent headers",
    accent: "#6694A5",
    pkg: "@preview/linked-cv",
    adapt: a_linked_cv,
  },
  {
    id: "mahou-cv",
    name: "Mahou CV",
    description: "Clean two-column CV with a pink accent and main/aside layout",
    accent: "#E16B8C",
    pkg: "@preview/mahou-cv",
    adapt: a_mahou_cv,
  },
  {
    id: "metronic",
    name: "Metronic",
    description: "Clean two-column CV with a colored sidebar and tag-style skills.",
    accent: "#2F6F8F",
    pkg: "@preview/metronic",
    adapt: a_metronic,
  },
  {
    id: "minimal-cv",
    name: "Minimal CV",
    description: "Clean two-column CV with gutter dates and accent section markers.",
    accent: "#0000b3",
    pkg: "@preview/minimal-cv",
    adapt: a_minimal_cv,
  },
  {
    id: "min-resume",
    name: "Minimal Resume",
    description: "Plain black-on-white sans-serif resume tuned for ATS and HR scanning",
    accent: "#333333",
    pkg: "@preview/min-resume",
    adapt: a_min_resume,
  },
  {
    id: "minimalistic-latex-cv",
    name: "Minimalistic LaTeX CV",
    description: "Clean LaTeX-style CV with smallcaps section rules and no color.",
    accent: "#333333",
    pkg: "@preview/minimalistic-latex-cv",
    adapt: a_minimalistic_latex_cv,
  },
  {
    id: "modern-acad-cv",
    name: "Modern Academic CV",
    description: "Academic CV with teal accent bars and a two-column date layout.",
    accent: "#579D90",
    pkg: "@preview/modern-acad-cv",
    adapt: a_modern_acad_cv,
  },
  {
    id: "modern-cv",
    name: "Modern CV",
    description: "Modern Awesome-CV port: centered name, accent headers, icon contacts",
    accent: "#262F99",
    pkg: "@preview/modern-cv",
    adapt: a_modern_cv,
  },
  {
    id: "modern-resume",
    name: "Modern Resume",
    description: "Colorful two-column CV with a ribbon header and skill pills",
    accent: "#449399",
    pkg: "@preview/modern-resume",
    adapt: a_modern_resume,
  },
  {
    id: "moderner-cv",
    name: "Moderner CV",
    description: "Clean moderncv-style CV with blue accent bars and social icons",
    accent: "#3973AF",
    pkg: "@preview/moderner-cv",
    adapt: a_moderner_cv,
  },
  {
    id: "modernpro-cv",
    name: "ModernPro CV",
    description: "Deedy-inspired professional single-column CV with serif headings.",
    accent: "#2b2b2b",
    pkg: "@preview/modernpro-cv",
    adapt: a_modernpro_cv,
  },
  {
    id: "mrbogo-cv",
    name: "MrBogo CV",
    description: "Modern two-column CV with navy header, sidebar skills bars, and blue accents.",
    accent: "#057dcd",
    pkg: "@preview/mrbogo-cv",
    adapt: a_mrbogo_cv,
  },
  {
    id: "neat-cv",
    name: "Neat CV",
    description: "Elegant two-column CV with a steel-blue header band and icon sidebar.",
    accent: "#4682b4",
    pkg: "@preview/neat-cv",
    adapt: a_neat_cv,
  },
  {
    id: "nabcv",
    name: "Not A Boring CV",
    description: "Two-column CV with a tinted sidebar and a timeline-style experience track.",
    accent: "#0D47A1",
    pkg: "@preview/nabcv",
    adapt: a_nabcv,
  },
  {
    id: "nutshell",
    name: "Nutshell",
    description: "Single-column resume with a date gutter and teal accents.",
    accent: "#095a5b",
    pkg: "@preview/nutshell",
    adapt: a_nutshell,
  },
  {
    id: "pesha",
    name: "Pesha",
    description: "Clean, minimal Butterick-inspired CV with centered header and ruled sections",
    accent: "#222222",
    pkg: "@preview/pesha",
    adapt: a_pesha,
  },
  {
    id: "porygon",
    name: "Porygon",
    description: "Two-column CV with a contact sidebar and blue accent icons.",
    accent: "#4a90d9",
    pkg: "@preview/porygon",
    adapt: a_porygon,
  },
  {
    id: "pro-academic-cv",
    name: "Pro Academic CV",
    description: "Professional serif academic CV with centered header and ruled sections.",
    accent: "#1a405d",
    pkg: "@preview/pro-academic-cv",
    adapt: a_pro_academic_cv,
  },
  {
    id: "rendercv",
    name: "RenderCV",
    description: "Clean academic/engineering CV with sectioned entries and a partial-line header",
    accent: "#004f90",
    pkg: "@preview/rendercv",
    adapt: a_rendercv,
  },
  {
    id: "resumania",
    name: "Resumania",
    description: "Minimalist single-column resume with bold section headers.",
    accent: "#333333",
    pkg: "@preview/resumania",
    adapt: a_resumania,
  },
  {
    id: "resume-ng",
    name: "Resume-ng",
    description: "Dense single-column serif resume with ruled section headings.",
    accent: "#333333",
    pkg: "@preview/resume-ng",
    adapt: a_resume_ng,
  },
  {
    id: "silver-dev-cv",
    name: "Silver Dev CV",
    description: "Recruiter-built serif CV with centered header and ruled sections",
    accent: "#2b2b2b",
    pkg: "@preview/silver-dev-cv",
    adapt: a_silver_dev_cv,
  },
  {
    id: "simple-technical-resume",
    name: "Simple Technical Resume",
    description: "Dense one-page ATS-friendly technical resume, Jake's-resume style.",
    accent: "#333333",
    pkg: "@preview/simple-technical-resume",
    adapt: a_simple_technical_resume,
  },
  {
    id: "simple-xd-resume",
    name: "Simple XD Resume",
    description: "Minimal black-and-white single-column resume tuned for ATS parsing",
    accent: "#333333",
    pkg: "@preview/simple-xd-resume",
    adapt: a_simple_xd_resume,
  },
  {
    id: "cv-soft-and-hard",
    name: "Soft And Hard",
    description: "Minimalist serif CV with ruled section headers and two-column entries.",
    accent: "#000000",
    pkg: "@preview/cv-soft-and-hard",
    adapt: a_cv_soft_and_hard,
  },
  {
    id: "sweet-graduate-resume",
    name: "Sweet Graduate Resume",
    description: "Compact teal-accented single-column resume for graduates and early-career roles",
    accent: "#78E6E6",
    pkg: "@preview/sweet-graduate-resume",
    adapt: a_sweet_graduate_resume,
  },
  {
    id: "toy-cv",
    name: "Toy CV",
    description: "Colorful two-column CV with a red header banner and icon sidebar.",
    accent: "#E40019",
    pkg: "@preview/toy-cv",
    adapt: a_toy_cv,
  },
  {
    id: "ttq-classic-resume",
    name: "TTQ Classic Resume",
    description: "Clean, dense classic resume with Garamond serif and ❖ contact line.",
    accent: "#333333",
    pkg: "@preview/ttq-classic-resume",
    adapt: a_ttq_classic_resume,
  },
  {
    id: "typographic-resume",
    name: "Typographic Resume",
    description: "Elegant two-column resume with a typographic aside and serif headings.",
    accent: "#3f454d",
    pkg: "@preview/typographic-resume",
    adapt: a_typographic_resume,
  },
  {
    id: "vercanard",
    name: "Vercanard",
    description: "Colorful two-column CV with a bold header and right sidebar",
    accent: "#4a7ba6",
    pkg: "@preview/vercanard",
    adapt: a_vercanard,
  },
  {
    id: "vivid-cv",
    name: "Vivid CV",
    description: "Design-forward ATS resume with a bold banner header and contact icons",
    accent: "#06332a",
    pkg: "@preview/vivid-cv",
    adapt: a_vivid_cv,
  },
  {
    id: "yuan-resume",
    name: "Yuan Academic",
    description: "Elegant academic CV with smallcaps section headings and serif type",
    accent: "#1a1a1a",
    pkg: "@preview/yuan-resume",
    adapt: a_yuan_resume,
  },
];

export const DEFAULT_TEMPLATE_ID = "vantage";

export const TEMPLATE_IDS: string[] = TEMPLATE_DEFS.map((t) => t.id);

export function getTemplateDef(id: string): TemplateDef {
  return TEMPLATE_DEFS.find((t) => t.id === id) ?? TEMPLATE_DEFS[0];
}

export function isTemplateId(id: unknown): id is string {
  return typeof id === "string" && TEMPLATE_IDS.includes(id);
}
